import time
from typing import Dict, Any, List
from pathlib import Path
import sys

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from core.agent.ReactiveLayer import ReactiveLayer


def demo_frames() -> List[Dict[str, Any]]:
    """Sample frames to demonstrate rule-based scenario detection + ML inference."""
    return [
        # Frame 1: Intersection scenario (detected by Lane being undefined and angle present)
        {
            "speed": 55.0,
            "acceleration": -0.7,
            "LeaderGap": 7.0,
            "LeaderSpeed": 30.0,
            "Lane": 0,  # Undefined lane -> intersection indicator
            "Angle": 30,  # Angle change -> intersection indicator
            "TTC": 1.9,
            "leading_vehicle": {"distance": 7.0, "speed": 30.0},
        },
        # Frame 2: Overtaking scenario (detected by lane change + SafeDistance + speed differential)
        {
            "speed": 78.0,
            "acceleration": 0.8,
            "LeaderGap": 15.0,
            "LeaderSpeed": 60.0,
            "Lane": 21,
            "LanePrev": 20,
            "lane_opposite_change": 1,  # Lane change indicator
            "SafeDistance": 12.0,  # Safe distance metric
            "TTC": 2.5,
            "leading_vehicle": {"distance": 15.0, "speed": 60.0},
        },
        # Frame 3: Danger zone scenario (detected by hard brake flag + low TTC)
        {
            "speed": 72.0,
            "acceleration": -1.2,
            "LeaderGap": 5.0,
            "LeaderSpeed": 0.0,  # Leader stopped
            "Lane": 21,
            "hard_brake": 1,  # Hard brake indicator
            "leader_stopped": 1,  # Leader stopped indicator
            "TTC": 2.8,
            "leading_vehicle": {"distance": 5.0, "speed": 0.0},
        },
    ]


def main() -> None:
    print("Starting Rule-Based Scenario Detection + ML Algorithm demo\n")
    reactive = ReactiveLayer()

    frames = demo_frames()
    for idx, frame in enumerate(frames, start=1):
        start = time.perf_counter()
        
        # Step 1: Show what scenario was detected by rules
        detected_scenario = reactive._detect_scenario(frame)
        
        # Step 2: Call ML algorithm for that scenario
        alert = reactive.check_immediate_danger(frame)
        elapsed_ms = (time.perf_counter() - start) * 1000

        print(f"\n{'='*60}")
        print(f"Frame {idx}")
        print(f"{'='*60}")
        print(f"  speed: {frame.get('speed', 0.0):.1f} km/h")
        print(f"  → Rule-detected scenario: {detected_scenario}")
        
        if alert is None:
            print(f"  ✅ No danger detected (risk_score < 0.55)")
        else:
            print(f"  ⚠️  Alert generated by {detected_scenario} ML model")
            print(f"     Type: {alert.type}")
            print(f"     Severity: {alert.severity.upper()}")
            print(f"     Message: {alert.message}")
            print(f"     Risk Score: {alert.parameters.get('risk_score', 'n/a'):.3f}")

        print(f"  Response time: {elapsed_ms:.2f} ms")


if __name__ == "__main__":
    main()